@startmindmap
* <b><:floppy_disk:> Классификация данных</b>\n<b>PropDevelopment</b>

left side

** <b>Данные клиентских</b>\n<b>сервисов</b>

*** <b>БД объектов\nнедвижимости</b>

**** <b><:computer:>Открытая часть БД</b>\n(внутренние данные)
*****[#yellow] потеря данных
*****[#yellow] искажение данных
*****[#lightgreen] устаревание данных
*****[#yellow] недоступность из-за DDoS

**** <b><:warning:> Закрытая часть БД</b>\n(конфиденциальные данные)

***** Неактивные карточки
******[#yellow] потеря данных
******[#yellow] искажение данных
******[#lightgreen] устаревание данных
******[#yellow] недоступность из-за DDoS
******[#yellow] утечка данных

***** Клиентская активность
******[#orange] утечка данных

***** Скидки и спецпредложения
******[#yellow] утечка данных

*** <b><:computer:> БД онлайн- и офлайн-туров</b>\n(внутренние данные)
****[#yellow] потеря/искажение данных
****[#yellow] недоступность из-за DDoS

*** <b><:no_entry:> БД сделок о недвижимости</b>\n(строго конфиденциальные)
****[#yellow] потеря данных
****[#orange] искажение данных
****[#red] утечка данных

*** <b><:warning:> БД CRM по клиентам</b>\n(конфиденциальные данные)
****[#orange] утечка данных
****[#lightgreen] потеря данных
****[#yellow] искажение данных
****[#yellow] устаревание данных

** <b>Данные сервисов</b>\n<b>собственников</b>

*** <b><:warning:> БД CRM по собственникам</b>\n(конфиденциальные данные)
****[#yellow] аналогично БД CRM\nпо клиентам

*** <b><:warning:> БД услуг ЖКХ</b>\n(конфиденциальные данные)

**** Данные поставщикам\nресурсов\n(конфиденциальные данные)
*****[#yellow] потеря/искажение данных
*****[#orange] утечка данных

**** Данные в БД\n(конфиденциальные данные)
*****[#yellow] аналогично предыдущим

**** Данные платёжной\nсистеме
*****[#yellow] потеря/искажение данных
*****[#yellow] утечка данных

**** Данные в БД\n(платёжные системы)\n(конфиденциальные данные)
*****[#yellow] потеря/искажение данных
*****[#orange] утечка данных

right side

** <b>Данные BI</b>

*** <b><:no_entry:> БД BI</b>\n(строго конфиденциально)
****[#lightgreen] потеря данных
****[#yellow] искажение данных
****[#red] утечка данных

** <b>Данные бухгалтерии</b>

*** <b><:warning:> БД финансового учёта</b>\n(конфиденциальные данные)
****[#lightgreen] потеря данных
****[#yellow] утечка данных

*** <b><:no_entry:> БД аутентификации бухгалтеров</b>\n(строго конфиденциально)
****[#yellow] потеря данных
****[#orange] утечка данных

** <b>Прочие данные</b>

*** <b><:no_entry:> БД сервиса аутентификации пользователей</b>\n(строго конфиденциально)
****[#red] утечка данных
****[#yellow] потеря данных

@endmindmap