apiVersion: audit.k8s.io/v1
kind: Policy
rules:
  - level: RequestResponse
    verbs: ["create", "delete", "update", "patch", "get", "list"]
    resources:
      - group: ""
        resources: ["pods", "secrets", "configmaps", "serviceaccounts"]
      - group: "rbac.authorization.k8s.io"
        resources: ["roles", "rolebindings", "clusterroles", "clusterrolebindings"]
  - level: Metadata
    resources:
      - group: ""
        resources: ["*"]
      - group: "apps"
        resources: ["*"]
      - group: "autoscaling"
        resources: ["*"]
      - group: "batch"
        resources: ["*"]
      - group: "certificates.k8s.io"
        resources: ["*"]
      - group: "events.k8s.io"
        resources: ["*"]
      - group: "networking.k8s.io"
        resources: ["*"]
      - group: "policy"
        resources: ["*"]
      - group: "scheduling.k8s.io"
        resources: ["*"]
      - group: "storage.k8s.io"
        resources: ["*"]
      - group: "apiextensions.k8s.io"
        resources: ["*"]