/*
Роли:
- Владелец
- Посетитель

Контексты взаимодействия:
- Владелец смотрит видео с камеры и определившийся номер авто
- Владелец открывает шлагбаум (разово)
- Владелец добавляет номер авто в список разрешённых

- Посетитель делает видеозвонок владельцу
- Посетитель автоматически проходит, если его номер авто в списке разрешённых
*/

@startuml
!include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Context.puml

LAYOUT_WITH_LEGEND()

title Контекстная диаграмма системы шлагбаума

Person(owner, "Владелец", "Владелец территории, управляет доступом")
Person(visitor, "Посетитель", "Человек, желающий попасть на территорию")

System_Ext(bar_gate_system, "Система шлагбаума", "Управляет доступом на территорию через шлагбаум")
System(mobile_app, "Мобильное приложение", "Приложение владельца для управления шлагбаумом")

'System_Ext(video_system, "Система видеонаблюдения и видеозвонков", "Камеры для наблюдения, распознавания номеров и видеосвязь")

Rel(owner, mobile_app, "Просматривает видео с камер")
Rel(owner, mobile_app, "Открывает шлагбаум вручную")
Rel(owner, mobile_app, "Управляет списком разрешённых номеров")

Rel(visitor, bar_gate_system, "Совершает видеозвонок владельцу")
Rel(visitor, bar_gate_system, "Проходит по номеру автомобиля")

Rel(mobile_app, bar_gate_system, "Управляет шлагбаумом")
'Rel(bar_gate_system, video_system, "Получает видео и данные о номерах авто")
'Rel(video_system, mobile_app, "Передаёт видео и видеозвонки")

@enduml