apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: sales-app-deployer-binding
  namespace: sales-services-prod
subjects:
- kind: Group
  name: sales-devops
  apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: Role
  name: sales-app-deployer
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: sales-app-deployer-binding
  namespace: sales-services-dev
subjects:
- kind: Group
  name: sales-devops
  apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: Role
  name: sales-app-deployer
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: sales-app-deployer-binding
  namespace: sales-services-test1
subjects:
- kind: Group
  name: sales-devops
  apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: Role
  name: sales-app-deployer
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: sales-app-deployer-binding
  namespace: sales-services-test2
subjects:
- kind: Group
  name: sales-devops
  apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: Role
  name: sales-app-deployer
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: sales-app-deployer-binding
  namespace: sales-services-test3
subjects:
- kind: Group
  name: sales-devops
  apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: Role
  name: sales-app-deployer
  apiGroup: rbac.authorization.k8s.io
